[git] Update subsplit and add hooks manager

diff --git a/git/2/rootfs/usr/libexec/git-core/git-subsplit b/git/2/rootfs/usr/libexec/git-core/git-subsplit
--- a/git/2/rootfs/usr/libexec/git-core/git-subsplit
+++ b/git/2/rootfs/usr/libexec/git-core/git-subsplit
@@ -3,9 +3,16 @@
 # git-subsplit.sh: Automate and simplify the process of managing one-way
 # read-only subtree splits.
 #
+# exit code:
+#   1 git add-remote/pull/fetch operation failed
+#   2 failed updating repo
+#   3 git push operation failed
+#   4 failed on git subtree command
+#
 # Copyright (C) 2012 Dragonfly Development Inc.
 #
 # Original file: https://github.com/dflydev/git-subsplit/blob/master/git-subsplit.sh
+# Applied patches: https://github.com/dflydev/git-subsplit/pull/23.patch
 # Applied patches: https://github.com/dflydev/git-subsplit/pull/24.patch
 #
 if [ $# -eq 0 ]; then
@@ -111,6 +118,15 @@ say()
 	fi
 }
 
+fatal()
+{
+	RC=${1:-1}
+	shift
+	say "${@:-## Error occurs}"
+	popd >/dev/null
+	exit $RC
+}
+
 subsplit_require_work_dir()
 {
 	if [ ! -e "$WORK_DIR" ]
@@ -189,7 +205,7 @@ subsplit_publish()
 
 		if ! git remote | grep "^${REMOTE_NAME}$" >/dev/null
 		then
-			git remote add "$REMOTE_NAME" "$REMOTE_URL"
+			git remote add "$REMOTE_NAME" "$REMOTE_URL" || fatal 1 "## Failed adding remote $REMOTE_NAME $REMOTE_URL"
 
 			if [ -n "$VERBOSE" ];
 			then
@@ -221,11 +237,11 @@ subsplit_publish()
 
 			say " - syncing branch '${HEAD}'"
 
-			git checkout master >/dev/null 2>&1
+			git checkout master >/dev/null 2>&1 || fatal 1 "## Failed while git checkout master"
 			git branch -D "$LOCAL_BRANCH" >/dev/null 2>&1
 			git branch -D "${LOCAL_BRANCH}-checkout" >/dev/null 2>&1
-			git checkout -b "${LOCAL_BRANCH}-checkout" "origin/${HEAD}" >/dev/null 2>&1
-			git subtree split -q --prefix="$SUBPATH" --branch="$LOCAL_BRANCH" "origin/${HEAD}" >/dev/null
+			git checkout -b "${LOCAL_BRANCH}-checkout" "origin/${HEAD}" >/dev/null 2>&1 || fatal 1 "## Failed while git checkout"
+			git subtree split -q --prefix="$SUBPATH" --branch="$LOCAL_BRANCH" "origin/${HEAD}" >/dev/null || fatal 4 "## Failed while git subtree split for HEADS"
 			RETURNCODE=$?
 
 			if [ -n "$VERBOSE" ];
@@ -251,7 +267,7 @@ subsplit_publish()
 					echo \# $PUSH_CMD
 					$PUSH_CMD
 				else
-					$PUSH_CMD
+					$PUSH_CMD || fatal 3 "## Failed pushing branchs to remote repo"
 				fi
 			fi
 		done
@@ -296,7 +312,7 @@ subsplit_publish()
 			fi
 
 			say " - subtree split for '${TAG}'"
-			git subtree split -q --annotate="${ANNOTATE}" --prefix="$SUBPATH" --branch="$LOCAL_TAG" "$TAG" >/dev/null
+			git subtree split -q --annotate="${ANNOTATE}" --prefix="$SUBPATH" --branch="$LOCAL_TAG" "$TAG" >/dev/null || fatal 4 "## Failed while git subtree split for TAGS"
 			RETURNCODE=$?
 
 			if [ -n "$VERBOSE" ];
@@ -319,7 +335,7 @@ subsplit_publish()
 					echo \# $PUSH_CMD
 					$PUSH_CMD
 				else
-					$PUSH_CMD
+					$PUSH_CMD || fatal 3 "## Failed pushing tags to remote repo"
 				fi
 			fi
 		done
@@ -334,9 +350,9 @@ subsplit_update()
 
 	say "Updating subsplit from origin"
 
-	git fetch -q -t origin
-	git checkout master
-	git reset --hard origin/master
+	git fetch -q -t origin || fatal 2 "## Failed updating repo"
+	git checkout master	+	git checkout master || fatal 2 "## Failed updating repo"
+	git reset --hard origin/master	+	git reset --hard origin/master || fatal 2 "## Failed updating repo"
 
 	if [ -n "$VERBOSE" ];
 	then
